## 异步编程

### 如何处理异常
- 异步发生的错误不需要抛出啦，可以作为callback的第一个参数传递给callback
- 实例写法
```
 
// 执行
function asyncError(callback){
  // 异步函数
  setImmediate(()=>{
    let err = null
    try{
      // 这里执行同步操作
      // 抛出错误
      throw new Error('errorMessage')
    }catch(v){
      // 捕捉错误
      err = v
    }
    // 作为第一个参数传递给callback
    callback(err)
  })
}

// 调用
asyncError(error => {
  console.log('-------: ', error)
})

```